export const SET_COORDS = 'SET_COORDS';

export const REQUEST_ROUTE = 'REQUEST_ROUTE';

export const LOAD_ROUTE_LOADING = 'LOAD_ROUTE_LOADING';
export const LOAD_ROUTE_SUCCESS = 'LOAD_ROUTE_SUCCESS';
export const LOAD_ROUTE_ERROR = 'LOAD_ROUTE_ERROR';
